import os

print("<!DOCTYPE html>")
print("<html>")
print("<head>")
print("<style>")
print("html	{")
print("height: 100%;")
print("}")
print("body	{")
print("height: 100%;")
print("width: 100%;")
print("text-align: center;")
print("}")
print("</style>")
print("</head>")
print("<body>")
print("<h1>" + os.environ.get("USERNAME") + "</h1>")
print("</body>")
print("</html>")
